version: "3"
services:
       login-app:
           container_name: node-docker
           image: node-docker
           restart: always
           build: .
           ports:
             - "3000:7500"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./EmployeeDB:/data/db
             ports:
               - '27018:27017'
